# Generated by Django 4.0.6 on 2022-08-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_user_article_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
