# Generated by Django 4.0.6 on 2022-09-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_cheked_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_cheked',
            new_name='is_checked',
        ),
    ]
