# Generated by Django 4.0.6 on 2022-08-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productcategory_product_cateogries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cateogries',
            new_name='categories',
        ),
    ]
