# Generated by Django 4.0.6 on 2022-08-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_image_productimage_product_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Излбражения товара'},
        ),
    ]
